"""Compatibility facade for Whisper block and segment assignment helpers."""

from . import whisper_assignment_trace as _trace
from . import whisper_block_dtw_assignments as _block_dtw
from . import whisper_segment_assignments as _segment

_json_safe_value = _trace._json_safe_value

_assign_lrc_lines_to_blocks = _block_dtw._assign_lrc_lines_to_blocks
_build_block_segmented_syllable_assignments = (
    _block_dtw._build_block_segmented_syllable_assignments
)
_build_block_word_bags = _block_dtw._build_block_word_bags
_group_syllables_by_block = _block_dtw._group_syllables_by_block
_run_per_block_dtw = _block_dtw._run_per_block_dtw
_syl_to_block = _block_dtw._syl_to_block

_SegmentAssignments = _segment._SegmentAssignments
_assign_lrc_lines_to_segments = _segment._assign_lrc_lines_to_segments
_append_segment_distribution_trace = _segment._append_segment_distribution_trace
_build_first_enclosing_segment_word_ranges = (
    _segment._build_first_enclosing_segment_word_ranges
)
_build_segment_text_overlap_assignments = (
    _segment._build_segment_text_overlap_assignments
)
_build_segment_word_info = _segment._build_segment_word_info
_collect_segment_lrc_word_indices = _segment._collect_segment_lrc_word_indices
_distribute_words_within_segments = _segment._distribute_words_within_segments
_finalize_segment_selection_trace = _segment._finalize_segment_selection_trace
_init_segment_selection_trace = _segment._init_segment_selection_trace
_merged_segment_candidate = _segment._merged_segment_candidate
_parse_trace_line_range_env = _segment._parse_trace_line_range_env
_rescue_terminal_stall_line_assignment = (
    _segment._rescue_terminal_stall_line_assignment
)
_rescue_zero_score_repeated_line_assignment = (
    _segment._rescue_zero_score_repeated_line_assignment
)
_score_segments_for_line = _segment._score_segments_for_line
_segment_assignment_config_from_env = _segment._segment_assignment_config_from_env
_segment_placeholder_ratio = _segment._segment_placeholder_ratio
_segment_search_window = _segment._segment_search_window
_select_segment_for_line_mode = _segment._select_segment_for_line_mode
_should_prefer_later_segment = _segment._should_prefer_later_segment
_text_overlap_score = _segment._text_overlap_score
_trace_later_merge_tiebreak = _segment._trace_later_merge_tiebreak
