"""Compatibility facade for lyrics helper functions."""

from .components.lyrics.helpers import (
    _apply_timing_to_lines,
    _apply_whisper_alignment,
    _clean_text_lines,
    _compress_spurious_lrc_gaps,
    _create_lines_from_plain_text,
    _create_no_lyrics_placeholder,
    _detect_and_apply_offset,
    _distribute_word_timing_in_line,
    _estimate_singing_duration,
    _extract_text_lines_from_lrc,
    _load_lyrics_file,
    _refine_timing_with_audio,
    _romanize_lines,
    create_lines_from_lrc,
    create_lines_from_lrc_timings,
    parse_lrc_with_timing,
    romanize_line,
)

__all__ = [
    "create_lines_from_lrc",
    "create_lines_from_lrc_timings",
    "parse_lrc_with_timing",
    "romanize_line",
    "_estimate_singing_duration",
    "_extract_text_lines_from_lrc",
    "_create_lines_from_plain_text",
    "_clean_text_lines",
    "_load_lyrics_file",
    "_create_no_lyrics_placeholder",
    "_detect_and_apply_offset",
    "_distribute_word_timing_in_line",
    "_apply_timing_to_lines",
    "_refine_timing_with_audio",
    "_compress_spurious_lrc_gaps",
    "_apply_whisper_alignment",
    "_romanize_lines",
]
