"""Whisper-based alignment and timing correction logic."""

import logging

from . import whisper_alignment_base
from . import whisper_alignment_segments
from . import whisper_alignment_refinement

logger = logging.getLogger(__name__)

# Basic timing adjustments
_enforce_monotonic_line_starts = whisper_alignment_base._enforce_monotonic_line_starts
_scale_line_to_duration = whisper_alignment_base._scale_line_to_duration
_enforce_non_overlapping_lines = whisper_alignment_base._enforce_non_overlapping_lines
_normalize_line_word_timings = whisper_alignment_base._normalize_line_word_timings
_apply_offset_to_line = whisper_alignment_base._apply_offset_to_line
_shift_line = whisper_alignment_base._shift_line
_line_duration = whisper_alignment_base._line_duration

# Segment-based alignment
_find_best_whisper_segment = whisper_alignment_segments._find_best_whisper_segment
_merge_lines_to_whisper_segments = (
    whisper_alignment_segments._merge_lines_to_whisper_segments
)
_retime_adjacent_lines_to_whisper_window = (
    whisper_alignment_segments._retime_adjacent_lines_to_whisper_window
)
_retime_adjacent_lines_to_segment_window = (
    whisper_alignment_segments._retime_adjacent_lines_to_segment_window
)
_pull_next_line_into_segment_window = (
    whisper_alignment_segments._pull_next_line_into_segment_window
)
_pull_next_line_into_same_segment = (
    whisper_alignment_segments._pull_next_line_into_same_segment
)
_merge_short_following_line_into_segment = (
    whisper_alignment_segments._merge_short_following_line_into_segment
)
_pull_lines_near_segment_end = whisper_alignment_segments._pull_lines_near_segment_end
_clamp_repeated_line_duration = whisper_alignment_segments._clamp_repeated_line_duration
_merge_first_two_lines_if_segment_matches = (
    whisper_alignment_segments._merge_first_two_lines_if_segment_matches
)
_tighten_lines_to_whisper_segments = (
    whisper_alignment_segments._tighten_lines_to_whisper_segments
)
_retime_line_to_segment = whisper_alignment_segments._retime_line_to_segment
_retime_line_to_segment_with_min_start = (
    whisper_alignment_segments._retime_line_to_segment_with_min_start
)
_retime_line_to_window = whisper_alignment_segments._retime_line_to_window
_pull_lines_to_best_segments = whisper_alignment_segments._pull_lines_to_best_segments
_drop_duplicate_lines = whisper_alignment_segments._drop_duplicate_lines

# High-level refinement and hybrid alignment
_calculate_drift_correction = whisper_alignment_refinement._calculate_drift_correction
_interpolate_unmatched_lines = whisper_alignment_refinement._interpolate_unmatched_lines
_refine_unmatched_lines_with_onsets = (
    whisper_alignment_refinement._refine_unmatched_lines_with_onsets
)
align_hybrid_lrc_whisper = whisper_alignment_refinement.align_hybrid_lrc_whisper
_fix_ordering_violations = whisper_alignment_refinement._fix_ordering_violations
_pull_lines_forward_for_continuous_vocals = (
    whisper_alignment_refinement._pull_lines_forward_for_continuous_vocals
)
_fill_vocal_activity_gaps = whisper_alignment_refinement._fill_vocal_activity_gaps
_drop_duplicate_lines_by_timing = (
    whisper_alignment_refinement._drop_duplicate_lines_by_timing
)

# Re-export from submodules for compatibility and patching
_check_vocal_activity_in_range = (
    whisper_alignment_refinement._check_vocal_activity_in_range
)
_check_for_silence_in_range = whisper_alignment_refinement._check_for_silence_in_range
